#!/usr/bin/env python3
"""Generate the pinned Unicode 14 full case-fold table used by the Node host."""

from __future__ import annotations

from pathlib import Path
import unicodedata


VERSION = "13.0.0"
ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src" / "adapters" / "okf" / "casefold.js"


def js_string(value: str) -> str:
    encoded = value.encode("unicode_escape").decode("ascii")
    return '"' + encoded.replace('"', '\\"') + '"'


def main() -> int:
    if unicodedata.unidata_version != VERSION:
        raise SystemExit(
            f"expected Unicode {VERSION}, got {unicodedata.unidata_version}"
        )
    rows = []
    for codepoint in range(0x110000):
        value = chr(codepoint)
        folded = value.casefold()
        if folded != value:
            rows.append(f"  [0x{codepoint:x}, {js_string(folded)}],")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        "\n".join(
            [
                '"use strict";',
                "",
                "// Generated by js/scripts/generate-casefold.py; Unicode 13.0.0.",
                "const CASE_FOLD = new Map([",
                *rows,
                "]);",
                "",
                "function casefold(value) {",
                '  let result = "";',
                "  for (const character of value) {",
                "    const replacement = CASE_FOLD.get(character.codePointAt(0));",
                "    result += replacement === undefined ? character : replacement;",
                "  }",
                "  return result;",
                "}",
                "",
                "module.exports = { casefold, UNICODE_VERSION: \"13.0.0\" };",
                "",
            ]
        ),
        encoding="utf-8",
        newline="\n",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
