# Explicit native-core build inputs. Keep paths sorted repository-relatively.
set(ARCHBIRD_DECLARED_CORE_SOURCE_PATHS
  src/act/act_accept.c
  src/act/act_apply.c
  src/act/act_gate_acceptance.c
  src/act/act_materialize.c
  src/act/act_model.c
  src/act/act_projection_acceptance.c
  src/act/act_requirements.c
  src/act/act_source.c
  src/act/act_submission.c
  src/act/c/declaration.c
  src/act/c/dependency_redirect.c
  src/act/c/napi_export.c
  src/act/c/provider_capability.c
  src/act/dependency_redirect.c
  src/act/ecmascript/dependency_redirect.c
  src/act/json/package_entrypoint.c
  src/act/make/provider_capability.c
  src/act/python/dependency_redirect.c
  src/act/python/rename.c
  src/act/rename.c
  src/api/act.c
  src/api/constraints.c
  src/api/map_reports.c
  src/api/plan.c
  src/api/project_configuration.c
  src/api/projection_reports.c
  src/api/query_plan.c
  src/api/source_reports.c
  src/base/artifact_validation.c
  src/base/base64.c
  src/base/date.c
  src/base/engine.c
  src/base/gate.c
  src/base/json.c
  src/base/json_number.c
  src/base/json_pointer_edit.c
  src/base/json_value.c
  src/base/make_variable_token_edit.c
  src/base/makefile.c
  src/base/model.c
  src/base/path_match.c
  src/base/pattern.c
  src/base/render.c
  src/base/sha256.c
  src/base/utf8.c
  src/configuration/project_configuration.c
  src/constraints/constraints.c
  src/evidence/config_json.c
  src/evidence/config_manifest_discovery.c
  src/evidence/config_resolution.c
  src/evidence/discovery.c
  src/evidence/evidence.c
  src/evidence/evidence_render.c
  src/evidence/fact_builder.c
  src/evidence/file_facts.c
  src/evidence/gitignore.c
  src/evidence/lexical/c/constants.c
  src/evidence/lexical/c/scanner.c
  src/evidence/lexical/javascript/scanner.c
  src/evidence/lexical/python/scanner.c
  src/evidence/lexical/r/scanner.c
  src/evidence/lexical/registry.c
  src/evidence/lexical/tokenizer.c
  src/evidence/manifests/autoconf_manifest.c
  src/evidence/manifests/cmake_project_manifest.c
  src/evidence/manifests/npm_workspace_manifest.c
  src/evidence/manifests/pyproject_manifest.c
  src/evidence/manifests/python_package_metadata.c
  src/evidence/manifests/setup_cfg_manifest.c
  src/evidence/project.c
  src/evidence/project/observation_store.c
  src/evidence/project/provider_merge.c
  src/evidence/project/provider_report.c
  src/evidence/project/provider_store.c
  src/evidence/project/source_store.c
  src/evidence/provider_registry.c
  src/evidence/python/definitions.c
  src/evidence/python/tokens.c
  src/evidence/semantic/registry.c
  src/evidence/semantic/scip/protobuf.c
  src/evidence/semantic/scip/scanner.c
  src/evidence/syntax/registry.c
  src/evidence/syntax/tree_sitter/c/scanner.c
  src/evidence/syntax/tree_sitter/cpp/scanner.c
  src/evidence/syntax/tree_sitter/ecmascript/module.c
  src/evidence/syntax/tree_sitter/ecmascript/scanner.c
  src/evidence/syntax/tree_sitter/javascript/scanner.c
  src/evidence/syntax/tree_sitter/python/scanner.c
  src/evidence/syntax/tree_sitter/r/scanner.c
  src/evidence/syntax/tree_sitter/scanner.c
  src/evidence/syntax/tree_sitter/tree_sitter_allocator.c
  src/evidence/syntax/tree_sitter/typescript/scanner.c
  src/evidence/test_observations.c
  src/interchange/diff/unified_diff.c
  src/interchange/graph/interchange_graph.c
  src/interchange/okf/okf.c
  src/interchange/okf/okf_model.c
  src/interchange/okf/okf_publish.c
  src/interchange/okf/okf_publish_bundle.c
  src/interchange/okf/okf_publish_map.c
  src/interchange/okf/okf_publish_model.c
  src/interchange/okf/okf_publish_util.c
  src/interchange/okf/okf_publish_verify.c
  src/interchange/okf/okf_query.c
  src/interchange/okf/okf_render.c
  src/interchange/reports/map_report.c
  src/interchange/reports/projection_reports.c
  src/interchange/reports/query_report.c
  src/interchange/reports/report_utils.c
  src/interchange/reports/source_report.c
  src/interchange/reports/verify_reports.c
  src/map/diff.c
  src/map/freshness.c
  src/map/map.c
  src/map/map_artifacts.c
  src/map/map_bridges.c
  src/map/map_builds.c
  src/map/map_checks.c
  src/map/map_facts.c
  src/map/map_indexes.c
  src/map/map_model.c
  src/map/map_named_entries.c
  src/map/map_packages.c
  src/map/map_parity.c
  src/map/map_references.c
  src/map/map_symbol_calls.c
  src/map/map_symbol_index.c
  src/map/map_symbol_references.c
  src/map/map_tests.c
  src/map/package_json.c
  src/map/workspace.c
  src/path/path.c
  src/path/path_artifact.c
  src/path/path_markdown.c
  src/plan/plan_compile.c
  src/plan/plan_compile_edge.c
  src/plan/plan_compile_finding.c
  src/plan/plan_compile_item.c
  src/plan/plan_compile_package.c
  src/plan/plan_compile_source.c
  src/plan/plan_compile_surface.c
  src/plan/plan_compile_symbol.c
  src/plan/plan_compile_test.c
  src/plan/plan_model.c
  src/plan/plan_report.c
  src/projection/component_membership.c
  src/projection/fact_projection.c
  src/projection/graph_projection.c
  src/projection/projection.c
  src/projection/projection_input.c
  src/projection/projection_model.c
  src/projection/projection_plan.c
  src/query/query_context.c
  src/query/query_execution.c
  src/query/query_plan.c
  src/query/query_projection.c
  src/query/retrieval.c
  src/transformation/rename_capability.c
  src/verify/verification_artifact.c
  src/verify/verify_authoring.c
  src/verify/verify_baseline.c
  src/verify/verify_checks.c
  src/verify/verify_context.c
  src/verify/verify_diagnostic.c
  src/verify/verify_observation.c
  src/verify/verify_render.c
)
